# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20160818_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(blank=True, null=True, related_name='abilities', to='pokedex.Ability'),
        ),
    ]
