# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='abilities', to='pokedex.Ability'),
        ),
    ]
